### ISSUE TITLE
Feature request: Closed captions support

### ISSUE THREAD

**Issue by spiral6** [cfinke/Channel-Two#2]
This one's more of a fun but not necessarily serious feature request: Closed captions support (not burned/embedded subtitles).

**Comment by cfinke** [comment]
👍  Definitely.

**Comment by cfinke** [comment]
I've added caption support; try it out when you can and let me know if I've missed something.

The bummer with this kind of "sometimes I want it enabled, sometimes I don't" feature is that because Channel Two is likely just being mirrored to a TV through HDMI or some other means, you can't turn on captions when the TV is muted (or selectively at all with the TV remote), since the computer running Channel Two has no knowledge of the TV.

But it's still nice to have. Thanks for the suggestion!
